WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers {
    [Authorize]
    public class AdminController : Controller {
        IBookRepository bookRepository;
        IOrderRepository orderRepository;

        public AdminController(IBookRepository bookRepo, IOrderRepository orderRepo) {
            bookRepository = bookRepo;
            orderRepository = orderRepo;
        }

        public ViewResult CreateBook() {
            return View("EditBook", new Book());
        }

        public ViewResult EditBook(int bookId) {
            Book book = bookRepository.Books
                .FirstOrDefault(g => g.Id == bookId);
            return View(book);
        }

        [HttpPost]
        public ActionResult EditBook(Book book, HttpPostedFileBase image = null) {
            if (ModelState.IsValid) {
                if (image != null) {
                    book.ImageMimeType = image.ContentType;
                    book.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(book.ImageData, 0, image.ContentLength);
                }
                bookRepository.SaveBook(book);
                TempData["message"] = string.Format("Изменения в игре \"{0}\" были сохранены", book.Name);
                return RedirectToAction("Index");
            } else {
                return View(book);
            }
        }

        [HttpPost]
        public ActionResult DeleteBook(int bookId) {
            Book deletedBook = bookRepository.DeleteBook(bookId);
            if (deletedBook != null) {
                TempData["message"] = string.Format("Книга \"{0}\" была удалена", deletedBook.Name);
            }
            return RedirectToAction("Index");
        }

        public ViewResult Index() {
            return View(bookRepository.Books);
        }

        public ViewResult ListOrders() {
            return View(orderRepository.Orders);
        }

        public ViewResult DeleteOrder(int orderId) {
            Order deletedOrder = orderRepository.DeleteOrder(orderId);
            if (deletedOrder != null) {
                TempData["message"] = string.Format("Заказ №{0} был удалён", deletedOrder.Id);
            }
            return View("ListOrders", orderRepository.Orders);
        }
    }
}

WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers {
    public class BookController : Controller {
        private IBookRepository repository;
        public int pageSize = 4;

        public BookController(IBookRepository repo) {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1) {
            if (genre != null)
                genre = genre.ToLower();

            IEnumerable<Book> books = repository.Books
                .Where(p => genre == null || p.Genre == genre);

            BookListViewModel model = new BookListViewModel {
                Books = books
                    .OrderBy(game => game.Id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = books.Count()
                },
                CurrentGenre = genre
            };
            return View(model);
        }

        [HttpPost]
        public ViewResult List(BookListViewModel model) {
            if (model == null)
                return List(null, 1);
            
            string search = model.SearchLine;
            string genre = model.CurrentGenre;
            if (search != null)
                search = search.ToLower();
            if (genre != null)
                genre = genre.ToLower();

            IEnumerable<Book> books = repository.Books
                .Where(p => genre == null || p.Genre.ToLower() == genre)
                .Where(p => search == null ||
                       p.Name.ToLower().Contains(search) || p.Author.ToLower().Contains(search));

            model = new BookListViewModel {
                Books = books
                    .OrderBy(game => game.Id)
                    .Take(pageSize),
                PagingInfo = new PagingInfo {
                    CurrentPage = 1,
                    ItemsPerPage = pageSize,
                    TotalItems = books.Count()
                },
                CurrentGenre = genre,
                SearchLine = search
            };
            return View(model);
        }

        public FileContentResult GetImage(int bookId) {
            Book book = repository.Books
                .FirstOrDefault(b => b.Id == bookId);

            if (book != null) {
                return File(book.ImageData, book.ImageMimeType);
            } else {
                return null;
            }
        }
    }
}

WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IBookRepository repo, IOrderProcessor processor) {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl) {
            return View(new CartIndexViewModel {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int bookId, string returnUrl) {
            Book book = repository.Books
                .FirstOrDefault(g => g.Id == bookId);

            if (book != null) {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl) {
            Book book = repository.Books
                .FirstOrDefault(g => g.Id == bookId);

            if (book != null) {
                cart.RemoveItem(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails) {
            if (cart.Lines.Count() == 0) {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid) {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            } else {
                return View(shippingDetails);
            }
        }

        public ViewResult Checkout() {
            return View(new ShippingDetails());
        }

        public PartialViewResult Summary(Cart cart) {
            return PartialView(cart);
        }
    }
}

WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace WebUI.Controllers
{
    public class NavController : Controller {
        private IBookRepository repository;

        public NavController(IBookRepository repo) {
            repository = repo;
        }

        public PartialViewResult Menu(string genre = null) {
            ViewBag.SelectedGenre = genre;
            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(genres);
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Login/css")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <div>
        @if (TempData["message"] != null) {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        <div class="navbar-collapse collapse">
            <ul class="nav nav-pills">
                <li id="home-tab">@Html.ActionLink("На главную", "List", "Book", null, null)</li>
                <li id="books-tab">@Html.ActionLink("Товары", "Index", "Admin")</li>
                <li id="orders-tab">@Html.ActionLink("Заказы", "ListOrders", "Admin")</li>
            </ul>
        </div>
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation" style="background-color: #428bca">
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="navbar-brand">
                    <img src="~/Images/book.png" width="60" height="60">
                    <a style="color: #ffffff">BookStore - магазин книг</a>
                </div>
            </div>
            <div class="nav navbar-nav navbar-right" style="line-height: 80px">
                <img src="~/Images/cart1.png" width="60" height="60" style="margin-right: 10px">
                @Html.Action("Summary", "Cart")
                @Html.ActionLink("Войти", "Login", "Account", null, new { style = "color: #ffffff; margin-left: 20px; margin-right: 20px" })
            </div>
        </div>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-6">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>